import {REVISION,NAMES,GPIO,check,adcValues,fitSweep,SweepDecoder,SweepPreview,electricalPoints,confirmedDut,b64encode,b64decode,crc32} from './protocol.js';
import {Journal} from './storage.js';
import {Controller,newId} from './controller.js';
import {NUS} from './transport.js';
import {DFU_SERVICE,DfuLink,firmwarePackage,DEFAULT_HASH} from './dfu.js';
import {readZip,writeZip,download,sha256} from './archive.js';
import {plot,fitText} from './plots.js';
const $=id=>document.getElementById(id),journal=new Journal();let controller,view=null,renderScheduled=false,dfuTarget=null,dfuPayload=null,dfuBusy=false,dfuLink=null,initializing=false,historyBusy=false,plotSignature=null;
const logLines=[];
function log(message){logLines.push(new Date().toLocaleTimeString()+'  '+message);if(logLines.length>200)logLines.shift();$('event-log').textContent=logLines.join('\n');}
const value=id=>$(id).value;
function status(text){if(text){$('status').textContent=text;log(text);}}
function changed(text){if(text)status(text);if(!renderScheduled){renderScheduled=true;requestAnimationFrame(()=>{renderScheduled=false;render();});}}
function button(id,fn){$(id).addEventListener('click',async()=>{try{await fn();}catch(e){status(e.message||e.name);}});}
function busy(){return initializing||dfuBusy||controller?.busy;}
function render(){
  if(!controller)return;const c=controller,connected=Boolean(c.transport.kind),ready=c.ready()&&!busy(),dut=confirmedDut(c.state,c.mux);
  $('usb-connect').disabled=$('ble-connect').disabled=connected||busy();$('disconnect').disabled=!connected||dfuBusy||initializing;$('safe').disabled=!connected||dfuBusy;
  document.querySelectorAll('[data-drive]').forEach(b=>b.disabled=!ready);$('vcmd-apply').disabled=!ready||dut===null;
  document.querySelectorAll('[data-connected]').forEach(b=>b.disabled=!connected||busy());$('monitor').disabled=busy();
  $('connection').textContent=connected?`${c.transport.kind.toUpperCase()} 연결 · ${c.readback?'설정 확인':'readback 미확인'}`:'장비가 연결되지 않았습니다.';
  $('route').textContent=dut!==null?`실제 연결: D${dut} · bank ${dut<=15?'A':'B'}`:c.mux&&c.mux[5]===0?'실제 연결: S16 parking · DUT 연결 해제':'실제 연결: 미확인';
  $('board').textContent=c.profile?`VER${c.firmware} · VrefB ${(c.profile.vref_b_mV/1000).toFixed(3)} V · SAFE ${(c.profile.safe_code*c.profile.vref_b_mV/4096).toFixed(1)} mV`:'보드 설정 미확인';
  if(c.limitReadback)$('cc-readback').textContent=`보드 CC+ ${(c.limitReadback[0]/1000).toFixed(3)} / CC− ${(c.limitReadback[1]/1000).toFixed(3)} mA · 명목값`+(c.driveReadback&&dut!==null?` · 최근 CTRL ${(c.driveReadback[2]/1000).toFixed(3)} mA ${c.driveReadback[3]?'PU':'PD'}`:'');
  if(c.raw){const a=adcValues(c.raw,c.adcInfo[0]);NAMES.forEach((_,i)=>{const [main,sub]=i===5?[`${a.current_mA.toFixed(3)} mA`,`V_IS ${a.volts[5].toFixed(4)} V`]:i===2||i===3?[`${(i===2?a.cc_plus_mA:a.cc_minus_mA).toFixed(3)} mA`,`기준 ${a.volts[i].toFixed(4)} V`]:[`${a.volts[i].toFixed(4)} V`,`raw ${c.raw[i]}`];$('adc-'+i).textContent=main;$('sub-'+i).textContent=sub+(c.raw[i]<0||c.raw[i]>=16364?' · 포화':'');});$('derived').textContent=`V_FB−V_MID ${a.feedback_V.toFixed(4)} V · TE_I−BE_I (FORCE) ${a.force_V.toFixed(4)} V · I ${a.current_mA.toFixed(3)} mA (4.0 Ω / gain20)`;$('adc-updated').textContent=`ADC ${c.adcInfo[0]}bit · 평균 ${c.adcInfo[1]}회 · ${new Date(c.adcAt).toLocaleTimeString()}`;}
  if(c.gpio){GPIO.forEach((_,i)=>{for(let j=0;j<2;j++){const e=$(`pin-${i}-${j}`),high=Boolean(c.gpio[j]&(1<<i));e.textContent=high?'HIGH':'LOW';e.className=high?'high':'low';}});$('gpio-info').textContent=`${new Date(c.gpioAt).toLocaleTimeString()} · ADG884 ${c.gpio[0]&(1<<9)?'PU':'PD'} · ${$('route').textContent}`;}
  if(c.capture){const x=c.capture;view={id:x.id,request:x.request,points:x.points,linear_fit:x.fit||fitSweep(x.points,x.request,x.fitLimit),crc_verified:x.crc_verified,safe_readback_confirmed:x.safe_readback_confirmed,outcome:'running',metadata:x.decoder.meta};}
  else if(c.lastCapture&&(!view||view.outcome==='running'))view=c.lastCapture;
  const points=view?.points||[],r=view?.request,fit=view?.linear_fit;
  const signature=[view?.id,points.length,view?.crc_verified,fit?.max_abs_V,view?.outcome].join(':');
  if(signature!==plotSignature){for(const kind of ['command','potential','sense'])plot($('plot-'+kind),points,r,kind,fit);plotSignature=signature;}
  $('fit-result').textContent=fitText(fit)+(view&&!view.crc_verified?'\n실시간 미리보기 · CRC 검증 전':'' );
  $('progress').max=r?.expected_points||1;$('progress').value=points.length;$('progress-text').textContent=r?`D${r.dut} · ${points.length}/${r.expected_points}점 · ${view.outcome==='running'?'진행 중':view.outcome} · CRC ${view.crc_verified?'확인':'미확인'} · SAFE ${view.safe_readback_confirmed?'확인':'미확인'}`:'측정 기록 없음';
  $('export-current').disabled=!view||busy();$('refit').disabled=busy();$('history-files').disabled=busy();
  for(const id of ['dfu-default','dfu-file','dfu-usb-pick','dfu-ble-pick'])$(id).disabled=busy();$('dfu-upload').disabled=!dfuTarget||!dfuPayload||busy()||connected;$('dfu-cancel').disabled=!dfuBusy;
}
function setTab(id){document.querySelectorAll('[role=tab]').forEach(b=>{const active=b.getAttribute('aria-controls')===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$(b.getAttribute('aria-controls')).hidden=!active;});changed();}
document.querySelectorAll('[role=tab]').forEach(b=>{b.addEventListener('click',()=>setTab(b.getAttribute('aria-controls')));b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...document.querySelectorAll('[role=tab]')],i=tabs.indexOf(b),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();setTab(tabs[next].getAttribute('aria-controls'));}});});
NAMES.forEach((name,i)=>{const card=document.createElement('div');card.className='adc-card';const title=document.createElement('div');title.className='adc-name';title.textContent=`AIN${i} · ${name}`;const main=document.createElement('div');main.className='adc-value';main.id='adc-'+i;main.textContent='—';const sub=document.createElement('div');sub.className='adc-sub';sub.id='sub-'+i;sub.textContent=[2,3,5].includes(i)?'mA · 전압 기반 추정':'V';card.append(title,main,sub);$('adc-cards').append(card);});
for(let i=1;i<=30;i++){const o=document.createElement('option');o.value=i;o.textContent=i;$('dut').append(o);}
GPIO.forEach(([signal,pin],i)=>{const row=document.createElement('tr');for(const text of [signal,pin]){const e=document.createElement('td');e.textContent=text;row.append(e);}for(let j=0;j<2;j++){const e=document.createElement('td');e.id=`pin-${i}-${j}`;e.textContent='—';row.append(e);}$('gpio-rows').append(row);});
async function connect(kind){check(!controller.transport.kind&&!busy(),'기존 연결 / 작업을 종료하세요.');check(window.isSecureContext,'HTTPS secure context 필요');check(kind==='usb'?'serial' in navigator:'bluetooth' in navigator,`${kind} API를 지원하지 않는 브라우저입니다.`);
  // Chooser is invoked directly in the click handler, before any awaited work.
  let selected;try{selected=kind==='usb'?await navigator.serial.requestPort():await navigator.bluetooth.requestDevice({filters:[{services:[NUS]}]});}catch(e){if(e.name==='NotFoundError')throw new Error('장비 선택이 취소됐습니다. USB/BLE 연결을 직접 누른 뒤 정확한 보드를 선택하세요. 아직 보드 명령은 전송하지 않았습니다.');throw e;}
  initializing=true;render();try{if(kind==='usb')await controller.connectUsb(selected);else await controller.connectBle(selected);}catch(e){await controller.transport.close();throw e;}finally{initializing=false;changed();}}
button('usb-connect',()=>connect('usb'));button('ble-connect',()=>connect('ble'));button('disconnect',()=>controller.disconnect());button('safe',()=>controller.safe());
button('dut-connect',()=>controller.connectDut(value('dut'),value('cc-plus'),value('cc-minus')));
button('vcmd-apply',()=>controller.applyVcmd(value('vcmd'),value('reference')==='absolute',value('cc-plus'),value('cc-minus')));
button('cc-apply',()=>controller.applyLimits(value('cc-plus'),value('cc-minus')));button('adc-once',()=>controller.adc());button('gpio-refresh',()=>controller.refresh());
button('monitor-apply',()=>controller.monitor($('monitor').checked?Math.round(Number(value('period'))*1000):0));
document.querySelectorAll('[data-endpoint]').forEach(b=>b.addEventListener('click',async()=>{const previous=controller.lastCapture?.id;try{const end=Number(b.dataset.endpoint);check(!busy(),'작업 중');if(!confirm(`D${value('dut')}: ${end>0?'+':''}${end/1000} V 왕복 sweep\nCC+ ${value('cc-plus')} mA / CC− ${value('cc-minus')} mA\n${value('step')} mV step, ${value('dwell')} ms dwell\n기존 연결은 S16을 거쳐 전환됩니다. 실행할까요?`))return;view=null;await controller.sweep(value('dut'),end,value('step'),value('dwell'),value('cc-plus'),value('cc-minus'),value('fit-limit'));}
  catch(e){status(e.message);}finally{if(controller.lastCapture&&controller.lastCapture.id!==previous){view=controller.lastCapture;try{await persistFiles(view);}catch(e){status('측정 기록 폴더 저장 실패 · IndexedDB 원시 보존: '+e.message);}}await history();changed();}}));
async function filesFor(run){const wire=await journal.wire(run.id),raw=run.raw_capture||new Uint8Array(),metadata={schema:'rram-web-sweep-v1',request:run.request,gui_revision:run.gui_revision,started_at_utc:run.started_at_utc,hardware_profile:run.hardware_profile,transport:run.transport,raw_unchanged:true};const {raw_capture,...result}=run;
  const csv=['point,target_mV,phase,start_us,end_us,AIN0,AIN1,AIN2,AIN3,AIN4,AIN5,AIN6,AIN7'];if(run.crc_verified){const d=new SweepDecoder(run.request);d.payload=raw;d.firmware=run.metadata.firmware;d.decode();for(const p of d.points)for(const f of p.frames)csv.push([p.index,p.target_mV,f.phase,f.start_us,f.end_us,...f.raw_codes].join(','));}
  const files={'metadata.json':metadata,'raw_wire.jsonl':wire.map(x=>JSON.stringify(x)).join('\n')+'\n','raw_capture.bin':raw,'raw_point_frames.csv':csv.join('\n')+'\n','electrical_points.json':{crc32:run.metadata.crc32,points:run.points},'linear_fit.json':run.linear_fit||{},'result.json':result};
  const hashes={};for(const [name,data] of Object.entries(files)){const b=data instanceof Uint8Array?data:new TextEncoder().encode(typeof data==='string'?data:JSON.stringify(data,null,2));hashes[name]=await sha256(b);}files['manifest.json']={schema:'rram-web-export-v1',run_id:run.id,sha256:hashes};return files;
}
async function persistFiles(run){if(journal.folder)await journal.saveFiles(run.id,await filesFor(run));}
async function exportRun(run){download(run.id+'.zip',writeZip(await filesFor(run)));status('raw / 분석 / SHA256 manifest ZIP 저장');}
button('export-current',()=>exportRun(view));
button('refit',async()=>{check(view&&view.request,'측정 기록이 없습니다.');check(!busy(),'측정 종료 후 근사 갱신');const f=fitSweep(view.points,view.request,value('fit-limit'));view={...view,linear_fit:f};changed('화면 근사 갱신 · DAC / GPIO 변경 없음');const analysis={id:newId('linear_fit_reanalysis'),kind:'analysis',source_run:view.id,started_at_utc:new Date().toISOString(),linear_fit:f};await journal.run(analysis);if(journal.folder)await journal.saveFiles(view.id,{[analysis.id+'.json']:analysis});});
async function history(){if(historyBusy)return;historyBusy=true;try{const all=(await journal.list()).filter(x=>x.kind==='sweep').sort((a,b)=>b.started_at_utc.localeCompare(a.started_at_utc));$('history-rows').replaceChildren();for(const run of all){const tr=document.createElement('tr');for(const text of [run.id,'D'+run.request.dut,`${run.request.endpoint_mV/1000} V`,run.points?.length||0,`${run.error||run.metadata?.status_text||run.outcome} / CRC ${run.crc_verified?'확인':'미확인'} / SAFE ${run.safe_readback_confirmed?'확인':'미확인'}`]){const td=document.createElement('td');td.textContent=String(text);tr.append(td);}const td=document.createElement('td');for(const [label,fn] of [['보기',()=>{check(!busy(),'현재 측정 종료 후 보기');view=run;setTab('control');}],['ZIP',()=>exportRun(run)]]){const b=document.createElement('button');b.textContent=label;b.addEventListener('click',()=>Promise.resolve().then(fn).catch(e=>status(e.message)));td.append(b);}tr.append(td);$('history-rows').append(tr);}if(!view&&all.length&&!controller.capture){view=all[0];changed();}}finally{historyBusy=false;}}
button('history-refresh',history);button('choose-folder',async()=>{await journal.directory();$('storage-info').textContent='IndexedDB raw 자동 저장 · 측정 종료 시 선택한 폴더에도 저장';});
async function importFiles(files){check(!busy(),'현재 작업 종료 후 가져오기');let entries=new Map();if(files.length===1&&files[0].name.endsWith('.zip'))entries=await readZip(new Uint8Array(await files[0].arrayBuffer()));else for(const f of files)entries.set(f.name,new Uint8Array(await f.arrayBuffer()));
  const get=name=>{const matches=[...entries.keys()].filter(k=>k===name||k.endsWith('/'+name));check(matches.length===1,`${name} 파일 하나가 필요합니다.`);return entries.get(matches[0]);},json=name=>JSON.parse(new TextDecoder().decode(get(name)));
  const metadata=json('metadata.json'),result=json('result.json'),raw=get('raw_capture.bin'),r=metadata.request||result.request;check(r&&raw.length>=304,'요청 metadata / raw capture 누락');const expected=result.metadata?.crc32;check(expected&&parseInt(expected,16)===crc32(raw),'가져온 raw / 저장된 CRC 불일치');
  const d=new SweepDecoder(r);d.payload=raw;d.firmware=result.metadata.firmware;check([81,82,83,84].includes(d.firmware),'SC81/82/83/84 native 기록만 지원');d.decode();d.complete=true;const points=electricalPoints(d),fit=fitSweep(points,r,value('fit-limit')),run={id:newId(`import_D${r.dut}`),kind:'sweep',request:r,started_at_utc:metadata.started_at_utc||new Date().toISOString(),gui_revision:REVISION,raw_capture:raw,metadata:d.meta,points,linear_fit:fit,crc_verified:true,safe_readback_confirmed:result.safe_readback_confirmed===true,outcome:d.meta.status===0?'complete':'guard_stop',imported:true,import_integrity:'raw file vs stored CRC; no new physical measurement'};
  const wireNames=[...entries.keys()].filter(k=>/(raw_wire|raw_sc_wire|raw_preview_wire)\.jsonl$/.test(k));let seq=0;for(const name of wireNames){const text=new TextDecoder().decode(entries.get(name));for(const s of text.split(/\r?\n/).filter(Boolean)){const rec=JSON.parse(s);await journal.append({...rec,run_id:run.id,seq:seq++,source_file:name});}}
  await journal.run(run);view=run;await history();setTab('control');status('저장 기록 불러옴 · 새 실측 아님');}
$('history-files').addEventListener('change',async e=>{try{await importFiles([...e.target.files]);}catch(err){status(err.message);}finally{e.target.value='';}});
async function loadPackage(bytes,name,isDefault=false){check(!busy(),'작업 중');const p=await firmwarePackage(bytes);if(isDefault)check(p.sha256===DEFAULT_HASH,'기본 firmware SHA256 불일치');dfuPayload=p;$('dfu-package').textContent=`${name} · app ${p.application.length} bytes · SHA256 ${p.sha256}`;render();}
$('dfu-file').addEventListener('change',async e=>{try{if(e.target.files[0])await loadPackage(new Uint8Array(await e.target.files[0].arrayBuffer()),e.target.files[0].name);}catch(err){dfuPayload=null;status(err.message);render();}});
button('dfu-default',async()=>{const response=await fetch('firmware/rram_backplane_app_v84_bleline_rramkey_signed.zip');check(response.ok,'기본 ZIP 파일 없음');await loadPackage(new Uint8Array(await response.arrayBuffer()),'v84 RRAM-key signed application',true);});
button('dfu-enter',async()=>{check(controller.ready()&&!busy(),'v84 연결 확인 및 작업 종료 필요');if(!confirm('SAFE readback 확인 후 DFU 진입합니다. 현재 연결은 종료됩니다. 계속할까요?'))return;await controller.safe();initializing=true;controller.expectedDisconnect=true;render();try{await controller.record({kind:'line',direction:'tx',source:controller.transport.kind,line:'DFU'});await controller.transport.send('DFU');await new Promise(r=>setTimeout(r,300));await controller.transport.close();controller.readback=false;status('DFU 진입 요청됨 · bootloader는 별도로 선택하세요.');}finally{initializing=false;controller.expectedDisconnect=false;render();}});
button('dfu-usb-pick',async()=>{check(!busy()&&!controller.transport.kind,'애플리케이션 연결을 종료하세요.');check('serial' in navigator,'Web Serial 미지원');const selected=await navigator.serial.requestPort({filters:[{usbVendorId:0x1915,usbProductId:0x521f}]});dfuTarget={kind:'usb',selected};$('dfu-target').textContent='선택됨: USB Secure DFU 1915:521f';render();});
button('dfu-ble-pick',async()=>{check(!busy()&&!controller.transport.kind,'애플리케이션 연결을 종료하세요.');check('bluetooth' in navigator,'Web Bluetooth 미지원');const selected=await navigator.bluetooth.requestDevice({filters:[{name:'DfuTarg',services:[DFU_SERVICE]}]});dfuTarget={kind:'ble',selected};$('dfu-target').textContent='선택됨: BLE '+selected.name;render();});
button('dfu-upload',async()=>{check(dfuPayload&&dfuTarget&&!busy()&&!controller.transport.kind,'ZIP과 bootloader 대상 선택 필요');if(!confirm(`${dfuTarget.kind.toUpperCase()} 대상에 선택한 서명 firmware를 전송합니다.\nSHA256 ${dfuPayload.sha256}\n웹 전송은 실물 검증 전입니다. 계속할까요?`))return;
  dfuBusy=true;render();const id=newId('dfu'),start=new Date().toISOString();let seq=0;
  try{await journal.run({id,kind:'dfu',started_at_utc:start,sha256:dfuPayload.sha256,outcome:'running'});dfuLink=new DfuLink(dfuTarget.kind,dfuTarget.selected,(direction,b)=>journal.append({run_id:id,seq:seq++,at_utc:new Date().toISOString(),direction,base64:b64encode(b)}));await dfuLink.open();await dfuLink.transfer(dfuPayload,(count,total,phase)=>{$('dfu-progress').max=total;$('dfu-progress').value=count;$('dfu-status').textContent=`${phase} · ${(100*count/total).toFixed(1)}%`;});$('dfu-status').textContent='DFU 전송 완료 · CRC/EXECUTE 확인 · 재연결 후 VER/HW 검증 필요';await journal.run({id,kind:'dfu',started_at_utc:start,finished_at_utc:new Date().toISOString(),sha256:dfuPayload.sha256,outcome:'transfer_complete'});}
  catch(e){$('dfu-status').textContent='DFU 실패: '+e.message+' · 자동 재시도 없음';await journal.run({id,kind:'dfu',started_at_utc:start,finished_at_utc:new Date().toISOString(),sha256:dfuPayload.sha256,outcome:'error',error:e.message});throw e;}
  finally{try{await dfuLink?.close();}finally{dfuLink=null;dfuBusy=false;dfuTarget=null;$('dfu-target').textContent='DFU 대상 재선택 필요';render();}}});
button('dfu-cancel',()=>{dfuLink?.cancel();status('DFU 취소 요청 · bootloader 상태에서 다시 연결해야 할 수 있습니다.');});
window.addEventListener('beforeunload',e=>{if(controller?.transport.kind||dfuBusy){e.preventDefault();e.returnValue='';}});
window.addEventListener('error',e=>{status('웹 callback 오류: '+e.message);if(controller?.transport.kind)controller.fault(e.error||new Error(e.message));});
async function boot(){try{await journal.open();if(navigator.storage?.persist)await navigator.storage.persist();$('storage-info').textContent='IndexedDB raw 자동 저장 활성 · 폴더 / ZIP은 별도 백업';controller=new Controller(journal,changed,log);const compatible=window.isSecureContext&&'serial' in navigator&&'bluetooth' in navigator;$('capabilities').textContent=compatible?'USB/BLE 선택 후 VER83(USB)/84(BLE)·ADC14·HW를 확인합니다. Python GUI에서 포트를 먼저 해제하세요.':'HTTPS 및 Web Serial / Web Bluetooth 지원 브라우저가 필요합니다. 연결 버튼에서 지원 여부를 확인합니다.';$('capabilities').classList.toggle('error',!compatible);status('준비 · 장비 미연결 · 웹 실물 검증 전');await history();render();}catch(e){$('capabilities').textContent='자동 저장 초기화 실패 · 구동 차단: '+e.message;$('capabilities').classList.add('error');status(e.message);}}
boot();
