import {BleAssembler,check} from './protocol.js';
export const NUS='6e400001-b5a3-f393-e0a9-e50e24dcca9e';
const RX='6e400002-b5a3-f393-e0a9-e50e24dcca9e',TX='6e400003-b5a3-f393-e0a9-e50e24dcca9e';
export class SerialChannel {
  constructor(port,onBytes,onClose){this.port=port;this.onBytes=onBytes;this.onClose=onClose;this.closing=false;this.writeChain=Promise.resolve();}
  async open(){await this.port.open({baudRate:115200,bufferSize:65536,flowControl:'none'});this.writer=this.port.writable.getWriter();this.reader=this.port.readable.getReader();await this.port.setSignals({dataTerminalReady:true,requestToSend:true});this.running=this.readLoop();}
  async readLoop(){let error;try{while(!this.closing){const {value,done}=await this.reader.read();if(done)break;if(value)await this.onBytes(value.slice());}}catch(e){if(!this.closing)error=e;}finally{this.reader.releaseLock();if(!this.closing)this.onClose(error||new Error('USB 연결 종료'));}}
  write(bytes){const p=this.writeChain.then(()=>this.writer.write(bytes));this.writeChain=p.catch(()=>{});return p;}
  async close(){this.closing=true;try{await this.reader?.cancel();}catch{}await this.running;await this.writeChain;try{this.writer?.releaseLock();await this.port.close();}catch{} }
}
export class BoardTransport {
  constructor(onBytes,onLine,onClose){Object.assign(this,{onBytes,onLine,onClose,kind:null,serial:null,device:null,rx:null});this.queue=Promise.resolve();this.sendChain=Promise.resolve();this.usbBuffer='';}
  enqueue(job){this.queue=this.queue.then(job).catch(e=>this.onClose(e));}
  async deliver(line){try{await this.onLine(line);}catch(e){await this.onClose(e);}} // Keep receiving SAFE/readback after a device/parser error. Drive stays interlocked.
  async receiveBle(b){await this.onBytes('ble',b);if(this.safeBarrier){check(b.every(x=>x<128),'BLE non-ASCII');if(new TextDecoder().decode(b).trim()!=='OK,SAFE')return;this.safeBarrier=false;this.assembler=new BleAssembler();await this.deliver('OK,SAFE');return;}const line=this.assembler.feed(b);if(line)await this.deliver(line);}
  async connectUsb(port){check(!this.kind,'이미 연결됨');this.kind='usb';try{this.serial=new SerialChannel(port,async b=>{await this.onBytes('usb',b);check(b.every(x=>x<128),'USB non-ASCII');this.usbBuffer+=new TextDecoder().decode(b);while(this.usbBuffer.includes('\n')){const end=this.usbBuffer.indexOf('\n'),line=this.usbBuffer.slice(0,end).replace(/\r$/,'');this.usbBuffer=this.usbBuffer.slice(end+1);check(line.length<=96,'USB record 길이');if(line)await this.deliver(line);}check(this.usbBuffer.length<=96,'USB delimiter 누락');},e=>this.onClose(e));await this.serial.open();}catch(e){await this.close();throw e;}}
  async connectBle(device){check(!this.kind,'이미 연결됨');this.kind='ble';this.device=device;this.assembler=new BleAssembler();this.disconnected=()=>{if(this.kind==='ble')this.onClose(new Error('BLE 연결 종료'));};device.addEventListener('gattserverdisconnected',this.disconnected);
    try{const server=await device.gatt.connect(),service=await server.getPrimaryService(NUS);this.rx=await service.getCharacteristic(RX);this.tx=await service.getCharacteristic(TX);this.safeBarrier=false;this.notification=e=>{const b=new Uint8Array(e.target.value.buffer,e.target.value.byteOffset,e.target.value.byteLength).slice();this.enqueue(()=>this.receiveBle(b));};this.tx.addEventListener('characteristicvaluechanged',this.notification);await this.tx.startNotifications();}catch(e){await this.close();throw e;}}
  send(command){check(this.kind,'장비 연결 필요');check(command.length<=47&&!/[\r\n]/.test(command),'명령 길이/개행');const kind=this.kind,rx=this.rx,serial=this.serial,bytes=new TextEncoder().encode(command+'\n');const work=this.sendChain.then(async()=>{check(this.kind===kind,'전송 중 연결 종료');if(kind==='usb')await serial.write(bytes);else{if(command==='SAFE'){this.safeBarrier=true;this.assembler=new BleAssembler();}for(let i=0;i<bytes.length;i+=20){const b=bytes.slice(i,i+20);if(rx.properties.write)await rx.writeValueWithResponse(b);else await rx.writeValueWithoutResponse(b);}}});this.sendChain=work.catch(()=>{});return work;}
  async close(){const serial=this.serial,device=this.device,tx=this.tx;this.kind=null;this.serial=null;this.device=null;this.rx=null;this.tx=null;this.usbBuffer='';if(device){device.removeEventListener('gattserverdisconnected',this.disconnected);tx?.removeEventListener('characteristicvaluechanged',this.notification);try{if(device.gatt.connected)await tx?.stopNotifications();}catch{}device.gatt.disconnect();}if(serial)await serial.close();this.queue=Promise.resolve();}
}
